#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)
#xrandr --auto
# 
#[ -f /etc/xprofile ] && . /etc/xprofile
#[ -f ~/.xprofile ] && . ~/.xprofile

## Merge Xresources. Mainly for urxvt
xrdb -merge ~/.Xresources

## Set the background to the one configured
sh ~/.fehbg &

## Start Dunst for notifications
dunst -mon 1 &

setxkbmap gb 

clipit &

## Udiskie to allow automount of USB. Not sure why there isn't a systemd service?
udiskie &

##Start xbindkeys to pick up key shortcuts/mouse
xbindkeys &
xmodmap ~/.xmodmap


## Start i3 Window Manager
exec i3 
##exec startxfce4
## 
## exec i3 -V >> ~/.i3/i3log >&1


