#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

# Should improve copy/pasta in some X apps.
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

export BROWSER=chromium

# Merge Xresources. Mainly for urxvt
xrdb -merge ~/.Xresources

# Set the background to the one configured
sh ~/.fehbg &

# Start Dunst for notifications
dunst -mon 1 &

setxkbmap gb 

#Start Dropbox Daemon
dropboxd &

#Start xbindkeys to pick up key shortcuts/mouse
xbindkeys &
xmodmap ~/.xmodmap

# Start i3 Window Manager
exec i3 -V >> ~/.i3/i3log >&1
